### ISSUE TITLE
`vcr::vcr_test_path` issue from vcr v1.0.0

### ISSUE THREAD

**Issue by sckott** [KKulma/intensegRid#32]
With the latest version of `vcr` just up to CRAN I unfortunately caused breaking changes for some packages depending on `vcr`. The function `vcr_test_path` is the issue. The change to that function worked for some, but it apparently has broken other packages. 

We have a proposed fix at https://github.com/ropensci/vcr/pull/236 Can you install that fork `remotes::install_github("dpprdan/vcr@fix/test_path")` and see if that fixes the problem?

**Comment by KKulma** [comment]
thanks for that, @sckott . Indeed, a new release breaks my R CMD check but your proposed fix.. well, fixes it 👍   
Is there any way it will make it to CRAN before the 5th of June (by then {intensegRid} will be taken down from CRAN)?

**Comment by sckott** [comment]
Thanks for checking it! Glad it works. We are still discussing this to make sure we're finding the best solution. Wait a bit longer and I'll get back to you. I plan to submit a fixed version soon, before June 5 - so you shouldn't have to submit a new version of your pkg.  Apologies for this headache!

**Comment by sckott** [comment]
A new version of `vcr` is on CRAN https://cloud.r-project.org/web/packages/vcr/ - CRAN checks for your package should be fixed soon once they are using the new version of `vcr`.

**Comment by KKulma** [comment]
Lovely, thanks for that! I'm delighted to close this issue 👍
